services:
  app:
    image: jekyll/minimal:4.1.0
    command: jekyll serve  --port 4567
    volumes:
      # - ./pages/jekyll:Z
      - type: bind
        source: $PWD
        target: /srv/jekyll
    ports:
      - 4567:4567
